sudo: false
language: c
script: make && make test

compiler:
  - clang
  - gcc
install:
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - clang
